import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
const out=new URL("../schemas/",import.meta.url); await mkdir(out,{recursive:true});
const str={type:"string",minLength:1}, digest={type:"string",pattern:"^[a-f0-9]{64}$"}, fp={type:"string",pattern:"^sha256:[a-f0-9]{64}$"}, time={type:"string",format:"date-time",pattern:"Z$"};
const strict=(required,properties)=>({type:"object",additionalProperties:false,required,properties});
const proto=(schema,required,properties)=>strict(["schema","schemaVersion","actionType",...required],{schema:{const:schema},schemaVersion:{const:"1.0.0"},actionType:{const:"agentproof.repository_patch.v1"},...properties});
const manifestEntry=strict(["path","mode","sha256","byteLength","exists","tracked"],{path:str,mode:{enum:["100644","100755"]},sha256:digest,byteLength:{type:"integer",minimum:0},exists:{type:"boolean"},tracked:{type:"boolean"}});
const identity=strict(["canonicalRoot","gitDirectorySha256","baseCommit","branch","headRef","remotesDigest","refsDigest"],{canonicalRoot:str,gitDirectorySha256:digest,baseCommit:str,branch:str,headRef:str,remotesDigest:digest,refsDigest:digest});
const operation={oneOf:[strict(["kind","path","contentBase64"],{kind:{const:"write"},path:str,contentBase64:{type:"string",pattern:"^[A-Za-z0-9+/]*={0,2}$"},mode:{enum:["100644","100755"]},newFile:{type:"boolean"}}),strict(["kind","path"],{kind:{const:"delete"},path:str})]};
const command=strict(["executable","args","cwd","timeoutMs","maxOutputBytes"],{executable:str,args:{type:"array",items:{type:"string"}},cwd:str,timeoutMs:{type:"integer",minimum:1,maximum:120000},maxOutputBytes:{type:"integer",minimum:1,maximum:1048576}});
const action=strict(["type","repositoryRoot","operations"],{type:{const:"agentproof.repository_patch.v1"},repositoryRoot:str,operations:{type:"array",minItems:1,items:operation},verificationCommands:{type:"array",items:command}});
const intent=strict(["summary","requestedBy","acceptanceCriteria"],{summary:str,requestedBy:str,acceptanceCriteria:{type:"array",items:{type:"string"}}});
const policy=strict(["allowedRepositoryRoot","allowedTrackedPaths","allowedNewPaths","maxPatchBytes","maxFiles"],{allowedRepositoryRoot:str,allowedTrackedPaths:{type:"array",items:str,uniqueItems:true},allowedNewPaths:{type:"array",items:str,uniqueItems:true},allowSecretBearingPaths:{type:"array",items:str,uniqueItems:true},allowedVerificationExecutables:{type:"array",items:str,uniqueItems:true},allowedVerificationWorkingDirectories:{type:"array",items:str,uniqueItems:true},maxPatchBytes:{type:"integer",minimum:1},maxFiles:{type:"integer",minimum:1}});
const approvalBinding=strict(["schemaVersion","transactionId","intentDigest","actionDigest","target","baseCommit","branch","beforeManifestDigest","proposedManifestDigest","patchDigest","expectedDiffDigest","affectedPaths","verificationPlanDigest","policyVersion","expiresAt","nonce"],{schemaVersion:{const:"agentproof.repository-patch.approval.v1"},transactionId:str,intentDigest:digest,actionDigest:digest,target:str,baseCommit:str,branch:str,beforeManifestDigest:digest,proposedManifestDigest:digest,patchDigest:digest,expectedDiffDigest:digest,affectedPaths:{type:"array",minItems:1,items:str,uniqueItems:true},verificationPlanDigest:digest,policyVersion:{const:"agentproof.repository-patch.v1"},expiresAt:time,nonce:str});
const approvalRequest=proto("agentproof.protocol.approval-request",["correlationId","transactionId","stateDirectory","preparedDigest","expiresAt","nonce","binding","requestDigest"],{correlationId:str,transactionId:str,stateDirectory:str,preparedDigest:digest,expiresAt:time,nonce:str,binding:approvalBinding,requestDigest:digest});
const approvalDecision=proto("agentproof.protocol.approval-decision",["correlationId","transactionId","requestDigest","preparedDigest","decision","authorityEnvironment","issuer","decidedAt","expiresAt","nonce","authorityPublicKeyPem","authorityFingerprint","approvalRequest","signatureBase64"],{correlationId:str,transactionId:str,requestDigest:digest,preparedDigest:digest,decision:{enum:["approved","denied"]},authorityEnvironment:{enum:["development","production"]},issuer:str,decidedAt:time,expiresAt:time,nonce:str,authorityPublicKeyPem:{type:"string",pattern:"^-----BEGIN PUBLIC KEY-----"},authorityFingerprint:fp,approvalRequest,signatureBase64:{type:"string",pattern:"^[A-Za-z0-9+/]+={0,2}$"}});
const executionEvidence=strict(["state","attemptedAt","completedAt","message"],{state:{enum:["executed","partially_executed","failed"]},attemptedAt:time,completedAt:time,message:str,executorProcessId:{type:"integer",minimum:1}});
const commandEvidence=strict(["executable","args","cwd","exitCode","timedOut","durationMs","stdoutDigest","stderrDigest","stdoutBytes","stderrBytes","truncated","sanitized"],{executable:str,args:{type:"array",items:{type:"string"}},cwd:str,exitCode:{type:["integer","null"]},timedOut:{type:"boolean"},durationMs:{type:"integer",minimum:0},stdoutDigest:digest,stderrDigest:digest,stdoutBytes:{type:"integer",minimum:0},stderrBytes:{type:"integer",minimum:0},truncated:{type:"boolean"},sanitized:{const:true}});
const verification=strict(["state","observedManifest","observedPaths","observedDiffDigest","identityUnchanged","unexpectedUntrackedPaths","commands","message"],{state:{enum:["verified","failed","uncertain"]},observedManifest:{type:"array",items:manifestEntry},observedPaths:{type:"array",items:str},observedDiffDigest:{oneOf:[digest,{type:"null"}]},identityUnchanged:{type:"boolean"},unexpectedUntrackedPaths:{type:"array",items:str},commands:{type:"array",items:commandEvidence},message:str});
const compensation=strict(["state","message","verifiedAt"],{state:{enum:["compensated","escalation_required"]},message:str,verifiedAt:time});
const readOnly=strict(["provider","command","status","success","resultDigest"],{provider:{const:"coding-agent-skills"},command:str,status:str,success:{type:"boolean"},resultDigest:digest});
const approvalV2=strict(["schemaId","transactionId","correlationId","originalTaskId","approvalTaskId","approvalDecisionId","approvedFromTaskId","intentDigest","actionDigest","preparedActionDigest","repositoryRoot","repositoryRootDigest","baseCommit","beforeStateDigest","proposedStateDigest","affectedPaths","policyVersion","issuer","decision","decidedAt","expiresAt","authorityEnvironment","nonce"],{schemaId:{const:"agentproof.approval-binding.v2"},transactionId:str,correlationId:str,originalTaskId:str,approvalTaskId:str,approvalDecisionId:str,approvedFromTaskId:str,intentDigest:digest,actionDigest:digest,preparedActionDigest:digest,repositoryRoot:str,repositoryRootDigest:digest,baseCommit:str,beforeStateDigest:digest,proposedStateDigest:digest,affectedPaths:{type:"array",minItems:1,items:str},policyVersion:str,issuer:str,decision:{const:"approved"},decidedAt:time,expiresAt:time,authorityEnvironment:{enum:["development","production"]},nonce:str});
const payload=strict(["schemaId","schemaVersion","receiptFormatVersion","actionType","receiptId","issuedAt","transactionId","correlationId","intentDigest","actionDigest","preparedActionDigest","repositoryRoot","repositoryRootDigest","repositoryIdentity","authorityEnvironment","policyVersion","approvalBinding","approvalBindingDigest","approvalDecisionDigest","approvalAuthorityEvidence","beforeStateDigest","proposedStateDigest","observedStateDigest","executionState","verificationState","compensationState","evidenceDigests","signerRole","signingPolicyId","predecessorPayloadDigest","evidence"],{schemaId:{const:"agentproof.signed-receipt.v2"},schemaVersion:{const:"2.0.0"},receiptFormatVersion:{const:"v2"},actionType:{const:"agentproof.repository_patch.v1"},receiptId:str,issuedAt:time,transactionId:str,correlationId:str,intentDigest:digest,actionDigest:digest,preparedActionDigest:digest,repositoryRoot:str,repositoryRootDigest:digest,repositoryIdentity:identity,authorityEnvironment:{enum:["development","production"]},policyVersion:{const:"agentproof.repository-patch.v1"},approvalBinding:approvalV2,approvalBindingDigest:digest,approvalDecisionDigest:digest,approvalAuthorityEvidence:{const:"receipt_signer_attests_portable_authority_verified"},beforeStateDigest:digest,proposedStateDigest:digest,observedStateDigest:digest,executionState:{enum:["executed","partially_executed","failed",null]},verificationState:{enum:["verified","failed","uncertain",null]},compensationState:{enum:["compensated","escalation_required",null]},evidenceDigests:strict(["readOnlyEvidenceDigest","executionEvidenceDigest","verificationEvidenceDigest","compensationEvidenceDigest"],{readOnlyEvidenceDigest:digest,executionEvidenceDigest:digest,verificationEvidenceDigest:digest,compensationEvidenceDigest:digest}),signerRole:{const:"independent_receipt_signer"},signingPolicyId:str,predecessorPayloadDigest:{oneOf:[digest,{type:"null"}]},evidence:strict(["intent","affectedPaths","beforeManifest","proposedManifest","observedManifest","readOnlyEvidence","execution","verification","compensation"],{intent,affectedPaths:{type:"array",minItems:1,items:str},beforeManifest:{type:"array",items:manifestEntry},proposedManifest:{type:"array",items:manifestEntry},observedManifest:{type:"array",items:manifestEntry},readOnlyEvidence:{type:"array",items:readOnly},execution:{oneOf:[executionEvidence,{type:"null"}]},verification:{oneOf:[verification,{type:"null"}]},compensation:{oneOf:[compensation,{type:"null"}]}})});
const proof=strict(["algorithm","keyId","publicKeyPem","signerFingerprint","payloadDigest","signatureBase64"],{algorithm:{const:"Ed25519"},keyId:str,publicKeyPem:{type:"string",pattern:"^-----BEGIN PUBLIC KEY-----"},signerFingerprint:fp,payloadDigest:digest,signatureBase64:{type:"string",pattern:"^[A-Za-z0-9+/]+={0,2}$"}});
const schemas={
  "repository-patch-request.schema.json":proto("agentproof.protocol.repository-patch-request",["correlationId","stateDirectory","action","intent","policy"],{correlationId:str,stateDirectory:str,action,intent,policy}),
  "prepared-repository-patch.schema.json":proto("agentproof.protocol.prepared-repository-patch",["correlationId","transactionId","stateDirectory","actionDigest","patchDigest","preparedDigest","state"],{correlationId:str,transactionId:str,stateDirectory:str,actionDigest:digest,patchDigest:digest,preparedDigest:digest,state:{const:"prepared"}}),
  "approval-request.schema.json":approvalRequest,
  "approval-decision.schema.json":approvalDecision,
  "execution-request.schema.json":proto("agentproof.protocol.execution-request",["correlationId","transactionId","stateDirectory","idempotencyKey","requiredAuthorityEnvironment","trustedAuthorityFingerprints","approvalDecision"],{correlationId:str,transactionId:str,stateDirectory:str,idempotencyKey:str,requiredAuthorityEnvironment:{enum:["development","production"]},trustedAuthorityFingerprints:{type:"array",minItems:1,items:fp,uniqueItems:true},approvalDecision}),
  "signed-receipt.schema.json":strict(["payload","proof"],{payload,proof}),
  "receipt-verification-result.schema.json":strict(["schema","schemaVersion","cryptographicallyValid","trusted","signerFingerprint","reason","verifiedClaims","unverifiedTransportMetadata","errors","warnings"],{schema:{const:"agentproof.protocol.receipt-verification-result"},schemaVersion:{const:"2.0.0"},cryptographicallyValid:{type:"boolean"},trusted:{type:"boolean"},signerFingerprint:{oneOf:[fp,{type:"null"}]},reason:{enum:["trusted","valid_untrusted_signer","legacy_unbound_receipt","invalid_structure","unsupported_version","digest_mismatch","invalid_signature","approval_binding_inconsistent","policy_mismatch","broken_predecessor_chain"]},verifiedClaims:{type:["object","null"]},unverifiedTransportMetadata:{type:"null"},errors:{type:"array",items:{type:"string"}},warnings:{type:"array",items:{type:"string"}}}),
  "transaction-status.schema.json":proto("agentproof.protocol.transaction-status",["correlationId","transactionId","state","receiptPersisted","lastError"],{correlationId:str,transactionId:str,state:{enum:["approval_required","blocked","prepared","executing","executed","partially_executed","verified","failed","uncertain","compensated","escalation_required"]},receiptPersisted:{type:"boolean"},lastError:{type:["string","null"]}}),
  "agent-proof-error.schema.json":proto("agentproof.protocol.error",["correlationId","code","message","retryable"],{correlationId:str,transactionId:str,code:str,message:str,retryable:{type:"boolean"}}),
};
for(const [name,schema] of Object.entries(schemas)) await writeFile(new URL(name,out),JSON.stringify({$schema:"https://json-schema.org/draft/2020-12/schema",$id:`https://agentproof.dev/schemas/2.0.0/${name}`,...schema},null,2)+"\n");
